common:
  vpn_cidr: "10.1.0.0/16"

workspaces:
  nonprod-us-west-1-default:
    aws:
      account_id: 897722682612
      region: us-west-1
    account_name: DhruvAdminRole
    project_name: terraform-basic-setup
